name: Leaderboard Creation 

on: push

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: create_output
        id: output
        run: |
          apt install pandoc 
          mkdir output # create output dir
          cp -R static output/static # copy static dir 
          convert.sh # convert files with pandoc
      
      - uses: actions/upload-artifact@master
        with:
          name: page
          path: output

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
      
    steps:
    - uses: actions/download-artifact@master
      with:
        name: page
        path: .
    - uses: actions/configure-pages@v1
    - uses: actions/upload-pages-artifact@v1
      with:
        path: .
    - id: deployment
      uses: actions/deploy-pages@main
 
