name: Leaderboard Creation 

on: push

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: create_output
        id: output
        run: |
          mkdir output # create output dir

      - uses: docker://pandoc/latex:2.9
        with:
          args: -s leaderboard.csv -o=output/index.html
      
      - uses: actions/upload-artifact@master
        with:
          name: page
          path: output

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
      
    steps:
    - uses: actions/download-artifact@master
      with:
        name: page
        path: .
    - uses: actions/configure-pages@v1
    - uses: actions/upload-pages-artifact@v1
      with:
        path: .
    - id: deployment
      uses: actions/deploy-pages@main
 
