name: Leaderboard Creation 

on: push

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: create_output
        id: output
        run: |
          mkdir output # create output dir
          cp -R static output/static # copy static dir      
      - uses: docker://pandoc/extra:latest
        with:
          args: -s -o output/index.html -f csv --metadata title="Real AI Leaderboard Prototype" --css=static/style.css --template=templates/default.html5 --include-after=static/style_tables.js leaderboard.csv
      
      - uses: actions/upload-artifact@master
        with:
          name: page
          path: output

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
      
    steps:
    - uses: actions/download-artifact@master
      with:
        name: page
        path: .
    - uses: actions/configure-pages@v1
    - uses: actions/upload-pages-artifact@v1
      with:
        path: .
    - id: deployment
      uses: actions/deploy-pages@main
 
